### PR TITLE
Added `gpt-4` and `gpt-4-32k` as available models for the Chat Completions endpoint.

### PR DESCRIPTION
**Pull request by claygriffiths**
Ticket: https://secure.helpscout.net/conversation/2229131097/47734?folderId=1530128

I would love to be able to pull these using the models endpoint as we do with the fine-tuned user models, but the response does not tell you which endpoint the models are available for.

## Screenshot

image

### CODE REVIEW

**Comment by spivurno** [comment]
I'm still on the waitlist for GPT-4 so I can't test actually responses but the UI works well. Only tweak I think we should make is that the tooltips for both `gpt-4` and `gpt-4-32k` use "our" in the following:

> Will be updated with our latest model iteration.

I'm assuming these were pulled from OpenAI's description of these models? It's a bit confusing though because it seems to indicate we are responsible for developing the models. I think we should consider replacing "our" with "the".

> Will be updated with the latest model iteration.

**Review by spivurno — APPROVED** [review]
Approved pending one bit of feedback above.

**Comment by spivurno** [comment]
Oh, also, should we make this Beta 2? Seems like a good marketing opportunity.

**Comment by claygriffiths** [comment]
@spivurno I don't think it's worth making it a beta 2. Ideally, these models would just show up automatically.

**Pull request merged**
