### PR TITLE
Add a filter to the OpenAI response.

### PR DESCRIPTION
**Pull request by mgratch**
The purpose of this PR is to add a filter to the OpenAI response.

1. I want to make sure it returns the appropriate content i.e. check for key words, or structure. In my current use case it is supposed to return JSON and if it doesn’t I can send it back to openai to try again.
1. In some cases responses can be longer than the maximum number of tokens and therefore the the `finish_reason` reason might not be `stop` and  in that case I send the response back with the additional message to “Continue previous response where you left off. Be aware if the previous response ended mid-sentence or in the middle of an html tag.”
1. If a dev modifies the request body to make it a streaming request, the response will need to be modified to handle this change.

I am sure other users can come up with additional use cases.

@spivurno and I have already discussed this.

### CODE REVIEW

**Comment by spivurno** [comment]
@claygriffiths Any objections? Here are some use cases from my discussion with @mgratch:

> 1. I want to make sure it returns the appropriate content i.e. check for key words, or structure. In my current use case it is supposed to return JSON and if it doesn’t I can send it back to openai to try again.
> 2. In some cases responses can be longer than the maximum number of tokens and therefore the the finish_reason reason might not be stop and  in that case I send the response back with the additional message to “Continue previous response where you left off. Be aware if the previous response ended mid-sentence or in the middle of an html tag.”

**Comment by mgratch** [comment]
I know this isn't a high priority. but figured I would remind y'all of it. @claygriffiths @spivurno

**Comment by spivurno** [comment]
Dude, sorry for the _super_ slow response time here. Got lost by the wayside and then struggled to prioritize due to Black Friday prep. 😜

**Comment by mgratch** [comment]
No problem at all! Thanks 🙏

**Pull request merged**
